/**
 * コンパイル済み artifact から ABI を取り出し、backend が読む生成物として書き出す。
 *
 *   npm run abi:export
 *
 * 出力先のファイルは生成物なので直接編集しない。コントラクトを変えたら
 * `npm run build && npm run abi:export` をやり直す。
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const outDir = path.resolve(root, '../backend/chat/src/integrations/chain/abi');

const targets = ['ChatCredit', 'ChatLogAnchor'] as const;

await mkdir(outDir, { recursive: true });

for (const name of targets) {
  const artifactPath = path.join(root, 'artifacts/contracts', `${name}.sol`, `${name}.json`);
  const artifact = JSON.parse(await readFile(artifactPath, 'utf8')) as { abi: unknown[] };

  const contents = `// Generated by contracts/scripts/exportAbi.ts. Do not edit.
export const ${name.charAt(0).toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

  const outPath = path.join(outDir, `${name}.ts`);
  await writeFile(outPath, contents, 'utf8');
  console.log(`wrote ${path.relative(root, outPath)}`);
}
